- name: install and start nginx
  hosts: web
  become: yes # -b
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
