- name: variables from file
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "course {{ COURSE }}, duration {{ DURATION }}, trainer {{ TRAINER }}"