- name: variables from file
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Enter course name
    private: false
  - name: DURATION
    prompt: Enter the duration
    private: false
  - name: TRAINER
    prompt: Enter trainer name
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "course {{ COURSE }}, duration {{ DURATION }}, trainer {{ TRAINER }}"